### ISSUE TITLE
Eu como município desejo, rematricular o equivalente a 40% do número de crianças e adolescentes que constarem como abandono no Censo Escolar em 2022 para que eu possa pontuar.

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#110]
Descrição: Rematricular o equivalente a 40% do número de  crianças e adolescentes que constarem como abandono  no Censo Escolar em 2022.

Regras de Pontuação (Atividade):

O Município pontua 2 pontos se e somente se entregar a "Atividade estiver completa" dentro do prazo.
Caso não atendam aos critério acima, não haverá pontuação.

Links úteis:

[Guia do SELO UNICEF](https://www.selounicef.org.br/sites/default/files/2021-09/053_Guia_Metodologico_Selo_FINAL_28_09_0.pdf)

**ABANDONO**
[Endpoint TRAJETÓRIA](https://trajetoriaescolar.org.br/wp-admin/admin-ajax.php?action=get_abandonos&municipio=2700201&year=2019)
-> Considerar apenas a quantidade existente na key: "total"

"abandonos": {
        **"total": 0,**
        "anos_iniciais": 0,
        "anos_finais": 0,
        "medio": 0,
        "municipal": {
            "total": 0,
            "anos_iniciais": 0,
            "anos_finais": 0,
            "medio": 0
        },

**REMATRÍCULAS**

**INITIAL_DATE:** 01/04/2023 
**ATÉ**
**FINAL_DATE:** 30/06/2024
**Comparar com os dados de 2021 do Endpont TRAJETORIAS**

[Endpoint BAE](https://api.buscaativaescolar.org.br/api/v1/lp/report/by_dates/city?ibge_id=2109452&initial_date=2021-10-31&final_date=2022-07-20)
-> Considerar apenas o atributo last_date quando o tipo for **"Cancelamento após (re)matrícula".**

{
    "goal": 58,
    "data": {
        "first_date": [],
        **"last_date":** [
            {
                "date": "2022-07-22",
                "value": "0",
                "tipo": "(Re)matrícula"
            },
            **{
                "date": "2022-07-22",
                "value": "140",
                "tipo": "Cancelamento após (re)matrícula"
            }**
        ]
    }
}

[Responsivo - referência ](https://xd.adobe.com/view/3c95ad06-7ecb-4c4d-90d8-0901ffb6c3db-69c6/grid)

[Protótipo - RS 2](https://xd.adobe.com/view/b76a2073-aeed-4198-a613-e1d35ec674f0-e239/)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

- [x] Município poderá filtrar o seu respectivo Município

- [x] Conter a descrição do que deve ser realizado na atividade 

- [x] Deve conter o prazo limite para realização da atividade

- [x] Uma barra de progresso da atividade em questão (Protocolos da Covid 19), deverá ser atualizada (em %), a medida que o Município avanca em suas atividades

- [x] Deve seguir as regras de pontuação estabelecidas.

- [x] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo.

- [ ] Deve rodar a busca dos dados 1x ao dia sempre apagando os dados e os inserindo novamente.
