### ISSUE TITLE
Eu como Município, Desejo visualizar o meu progresso da Formação, para que eu possa realiza-la dentro do prazo.

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#42]

**Comment by lucasferreiraunicef** [comment]
Descrição: 
Apresentar certificados das capacitações em água, saneamento e promoção de
higiene nas escolas e unidades de saúde para a prevenção e controle da Covid-19
de, no mínimo, 1 servidor público da área de educação, 1 da área de saúde e 1 da
área de assistência social.

OU

Apresentar certificados das capacitações em direitos humanos a água e esgotamento sanitário; política de saneamento básico no Brasil; promoção de higiene; lavagem de mãos; dignidade e higiene menstrual; gênero e acesso à água; e metodologias participativas de gestão comunitária da água de, no mínimo, 1 servidor público da área de educação, 1 da área de saúde e 1 da área de assistência social e, sempre que possível, de uma pessoa responsável pela prestação do serviço de água e esgoto no município.


**Regras de Pontuação (Atividade):**
O Município pontua 2 pontos se e somente se os "Servidores Municipais" apresentarem certificados das capacitacões em água, saneamento e promoção de
higiene nas escolas e unidades de saúde para a prevenção e controle da Covid-19 de no mínimo 1 servidor da área de educação, saúde e assistência social.

________________________________________________________________________

**Links úteis:**

[Lista de Escolas por Município](https://unicef.sharepoint.com/:x:/r/sites/BRA/_layouts/15/Doc.aspx?sourcedoc=%7B70FE451D-EDF3-47BF-9669-2E2C19D8F54B%7D&file=Lista_Escolas_2020.xlsx&action=default&mobileredirect=true)

[Guia do SELO UNICEF](https://www.selounicef.org.br/sites/default/files/2021-09/053_Guia_Metodologico_Selo_FINAL_28_09_0.pdf)

[Protótipo](https://xd.adobe.com/view/e79b774a-acbb-4f22-b862-e165a0a3f345-b2c8/screen/48b5d0c4-09aa-41d1-9dd1-544990469c54) - **Considerar somente a tela 7**

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

- [x] Município poderá filtrar o seu respectivo Município

- [x] Conter a descrição do que deve ser realizado na atividade 

- [ ] Deve conter o prazo limite para realização da atividade

- [x] Uma barra de progresso da atividade em questão (Protocolos da Covid 19), deverá ser atualizada (em %), a medida que o Município avanca em suas atividades

- [ ] Deve seguir as regras de pontuação estabelecidas.

- [ ] `Conter todos os componentes de tela prototipados.`
