### ISSUE TITLE
Adesão BAV 1

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#430]
Description: Pelo menos 2 profissionais de qualquer cargo/ocupação realizando o curso de Título: **Busca Ativa Vacinal - Coordenador Operacional e Gestor de Políticas Públicas** 

- Gestor(a) da Política Pública da BAV
- Coordenador(a) Operacional Municipal da BAV

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [ ] Conter a jornada de usuário completa.

 

- [ ] Todas as validações de campo devem estar funcionando.

 

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [ ] Deve ser aceito e aprovado em homologação.
