### ISSUE TITLE
Eu como Município, Desejo visualizar o progresso da Meta "Programa de Lavagem de Mãos""

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#45]

**Comment by lucasferreiraunicef** [comment]
**Descrição:**
Implantar Programa de Lavagem de Mão se higiene para crianças e adolescentes
na pré-escola e séries iniciais do ensino fundamental, praticando a higiene com
pias, água, sabão e lavagem de mãos em pelo menos 10% das escolas do município.

**Prazo**: 30 de junho de 2023.

________________________________________________________________________

**Links úteis:**

[Lista de Escolas por Município](https://unicef.sharepoint.com/:x:/r/sites/BRA/_layouts/15/Doc.aspx?sourcedoc=%7B70FE451D-EDF3-47BF-9669-2E2C19D8F54B%7D&file=Lista_Escolas_2020.xlsx&action=default&mobileredirect=true)

[Lista de Municípios Inscritos no Selo](https://unicef.sharepoint.com/:x:/r/sites/BRA/_layouts/15/Doc.aspx?sourcedoc=%7B2ED55E3C-BFDC-4497-B8F3-FCDF3DA1F6F4%7D&file=Inscritos.xlsx&action=default&mobileredirect=true)


[Guia do SELO UNICEF](https://www.selounicef.org.br/sites/default/files/2021-09/053_Guia_Metodologico_Selo_FINAL_28_09_0.pdf)

[Protótipo](https://xd.adobe.com/view/e79b774a-acbb-4f22-b862-e165a0a3f345-b2c8/screen/48b5d0c4-09aa-41d1-9dd1-544990469c54) - **Considerar somente a tela 7**

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

- [ ] Município poderá filtrar o seu respectivo Município

- [ ] Conter a descrição do que deve ser realizado na atividade 

- [ ] Deve conter o prazo limite para realização da atividade

- [ ] Uma barra de progresso da atividade em questão (Protocolos da Covid 19), deverá ser atualizada (em %), a medida que o Município avanca em suas atividades

- [ ] Deve seguir as regras de pontuação estabelecidas.

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo.

- [ ] Deve rodar a busca dos dados 1x ao dia sempre apagando os dados e os inserindo novamente.
