### ISSUE TITLE
Eu como Município, Desejo visualizar a pontuacão final do Resultado Sistemico para identificar se atingimos o esperado.

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#46]

**Comment by lucasferreiraunicef** [comment]
**Descrição:** 
Ao final do prazo do **RESULTADO SISTÊMICO**, o Município deve identificar dentro do portal qual a pontuação final do RS.

**Regras de Pontuação (Atividade):**

Se o município não realizou a ação prevista,
não alcançou a meta e/ou não apresentou os
documentos solicitados. **A Pontuação será ZERO.**
Exemplo: Se o Município não entregou nenhuma das atividades do RS3, Wash, Checklist e etc, o município não pontua.

Se o município realizou a ação prevista, alcançou
a meta e apresentou os documentos solicitado
fora do prazo indicado. **A Pontuação será 1.**
Exemplo: Se o Município conseguiu atingir a meta, mas entregou as atividades fora do prazo. O Município recebe apenas 1 Ponto.

Se o município realizou a ação prevista, alcançou
a meta e apresentou os documentos solicitados
nos prazos definidos. **A Pontuação será 2.**
Exemplo: Se o Município entregou todas as atividades do RS atingindo a Meta + Entregando dentro do prazo, o Município recebe 2 pontos.


**Regras de Pontuação Geral:**
* Atividades entregues dentro do prazo -> **Resultado Sistêmico = 2 Pontos**
* Atividades entregues fora do prazo -> **Resultado Sistêmico = 1 Ponto**
* Nenhum atividade entregue -> **Resultado Sistêmico = 0 Pontos**

________________________________________________________________________

**Links úteis:**

[Lista de Escolas por Município](https://unicef.sharepoint.com/:x:/r/sites/BRA/_layouts/15/Doc.aspx?sourcedoc=%7B70FE451D-EDF3-47BF-9669-2E2C19D8F54B%7D&file=Lista_Escolas_2020.xlsx&action=default&mobileredirect=true)

[Lista de Municípios Inscritos no Selo](https://unicef.sharepoint.com/:x:/r/sites/BRA/_layouts/15/Doc.aspx?sourcedoc=%7B2ED55E3C-BFDC-4497-B8F3-FCDF3DA1F6F4%7D&file=Inscritos.xlsx&action=default&mobileredirect=true)


[Guia do SELO UNICEF](https://www.selounicef.org.br/sites/default/files/2021-09/053_Guia_Metodologico_Selo_FINAL_28_09_0.pdf)

[Protótipo](https://xd.adobe.com/view/e79b774a-acbb-4f22-b862-e165a0a3f345-b2c8/screen/48b5d0c4-09aa-41d1-9dd1-544990469c54) - **Considerar somente a tela 7**

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

- [ ] Município poderá filtrar o seu respectivo Município

- [ ] Mostrar a quantidade de pontos atingida ao final do prazo do Resultado Sistêmico.

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo.

- [ ] Deve rodar a busca dos dados 1x ao dia sempre apagando os dados e os inserindo novamente.
