### ISSUE TITLE
Adesão BAV 2

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#489]
Description: Verificar se determinado município possui cadastrado os seguintes colaboradores com seus respectivos cargos abaixo.

**Cadastro da equipe na plataforma** 
- Gestor(a) da Política Pública da BAV (JSON: gestor_politico)
- Coordenador(a) Operacional Municipal (BAV: Coordenador(a) operacional da saúde)
- Agente de alerta
- Técnico verificador
- Supervisor(a) institucional da assistência social
- Supervisor(a) institucional da saúde
- Supervisor(a) institucional da educação

[Endpoint - Teste](https://api.testes.buscaativavacinal.org.br/api/accession/selo)

**How**
curl --request GET \
  --url https://api.buscaativavacinal.org.br/api/accession/selo \
  --header 'Accept: application/json' \
  --header 'Authorization-Selo: $2y$13$B39XqXyn7oKBgYnkxuapzOm6/qvpiKqeo.l5kHT1XRLZqVOuCmwU' \
  --header 'Content-Type: application/json'

**Obs**: lembrando que precisamos informar o header: Authorization-Selo, mesmo que for vazio.

Token:

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [ ] Conter a jornada de usuário completa.

 

- [ ] Todas as validações de campo devem estar funcionando.

 

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [ ] Deve ser aceito e aprovado em homologação.
