### ISSUE TITLE
[FIX] Programa de Lavagem de mãos *

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#494]
**Dependencies:** ISSUE #45

**Description:** 

**1 Etapa -> PCJ
2 Etapa -> Pesquisas**

1 Atividade + 2 subtasks

**Atividade 1 - PCJ (SUBTASK 1)**
Title: PCJ - Atividade - Implantar Programa Lavagem de Mãos e Higiene para Crianças e Adolescentes na Pré-Escola e Séries Iniciais do Ensino Fundamental

**Atividade 2 - Plataforma de Pesquisas (SUBTASK 2)**
Title: https://pesquisas.unicef.org.br/pesquisa/26

**Regra:**

PCJ - Portaria postada na PCJ implantando o Programa de Lavagem de Mãos

Pesquisa -10% das escolas do município implantando o Programa de Lavagem de Mãos em escolas da rede Municipal ÁREA URBANA + ÁREA RURAL,segue passo a passo:

Verificar se as escolas (Quantidade de escolas recuperada da API de pesquisas) correspondem a 
10% das escolas da rede municipal total (rural + urbana - verificar na planilha abaixo)

**Planilha:**
https://app.zenhub.com/files/470778489/32d313de-34b5-4d2d-ac24-753ec1709fff/download

[Endpoint](https://pesquisas.unicef.org.br/pesquisa/26)

**Comment by lucasferreiraunicef** [comment]
Critérios de aceite:

 

- [ ] Conter a jornada de usuário completa.

 

- [ ] Todas as validações de campo devem estar funcionando.

 

- [ ] Deve Conter todos os componentes de tela desenvolvidos com base no protótipo da sprint atual.

 

- [ ] Deve ser aceito e aprovado em homologação.

**Comment by lucasferreiraunicef** [comment]
1 Atividade + 2 subtasks

Atividade 1 - PCJ 
Title: PCJ - Atividade - Implantar Programa Lavagem de Mãos e Higiene para Crianças e Adolescentes na Pré-Escola e Séries Iniciais do Ensino Fundamental

Atividade 2 - Plataforma de Pesquisas 
Title: https://pesquisas.unicef.org.br/pesquisa/26

**Regra:** 

1) PCJ - Portaria postada na PCJ implantando o Programa de Lavagem de Mãos 

 

2) Pesquisa -10% das escolas do município implantando o Programa de Lavagem de Mãos

 

**Prazo da atividade: 31/10/2023** 

Meta Calculada:
[https://app.zenhub.com/files/470778489/32d313de-34b5-4d2d-ac24-753ec1709fff/download](https://app.zenhub.com/files/470778489/32d313de-34b5-4d2d-ac24-753ec1709fff/download)

**Comment by lucasferreiraunicef** [comment]
@dlazaroni 
Inserir as segujntes subtasks dentro do card de "LAVAGEM DE MÃOS - RS 3", obs: O texto deverá permanecer o mesmo.

**Atividade 1 - PCJ (SUBTASK 1)**
Title: PCJ - Atividade - Implantar Programa Lavagem de Mãos e Higiene para Crianças e Adolescentes na Pré-Escola e Séries Iniciais do Ensino Fundamental

**Atividade 2 - Plataforma de Pesquisas (SUBTASK 2)**
