### ISSUE TITLE
Análise SELO

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#594]
- [x] **CRAS ofertando serviços de atenção à Primeira Infância (Censo SUAS)**

DataLake

_________________________________________________________________________________________________

- [x] **Profissionais certificados em 4 cursos sobre Educação Infantil**

RS 1
Planilha + AVA

_________________________________________________________________________________________________

- [x] **Profissionais certificados nos cursos Gestão Escolar e Professores na Rede ou Gestão Educacional na Rede**

RS 2
Planilha + AVA

_________________________________________________________________________________________________

- [x] **Profissionais certificados no curso Práticas de Alfabetização em Contextos de Multiletramentos**

RS 2
Planilha + AVA

_________________________________________________________________________________________________

- [x] **Centro de Referência da Assistência Social (CRAS) em articulação com os serviços de Educação e Saúde (Censo SUAS)**

RS 7 
DATALAKE

_________________________________________________________________________________________________

- [x] **Centro de Referência da Assistência Social (CRAS) em articulação com os serviços de Educação, Saúde e Proteção Especial (Censo SUAS)**

RS 7
DATALAKE

_________________________________________________________________________________________________

- [x] **INDIQUE 2 MEDICÃO**

RS 1
PESQUISAS -> 
https://api.pesquisas.unicef.org.br/api/responses/paginated/29?page=1

**

> ATENCÃO: VERIFICAR SE A PLANILHA É A MESMA DO INDIQUE 1

**

_________________________________________________________________________________________________

- [ ] **PMPI Implementado**

RS 1
PCJ -> Atividade - Plano Municipal pela Primeira Infância Implementando no Município - 2023
