### ISSUE TITLE
CRAS RS 7

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#664]
**Vamos utilizar os seguintes indicadores do DATALAKE:**

- Número de CRAS com forte articulação (municipios de porte médio e grande)
- Número de CRAS com forte articulação (municipios de porte pequeno I e II)
- Número total de CRAS por município

Link: https://sdmx.data.unicef.org/databrowser/index.html?q=BRAZIL_CO:BRAZIL_CO_SELO(1.0);.CRAS_FORTE_ART_MEDIO_GRANDE_PORTE+CRAS_FORTE_ART_PQ_PORTE+NUM_CRAS_TOTAL...

---

**1. Municípios de pequeno porte (aplicar no card atual):**
Utilizar:

- [ ] **Alterar Fonte de dados:**

- Número de CRAS com forte articulação (municipios de porte pequeno I e II)
- Número total de CRAS por município (pegar o dado do ano do indicador acima, no caso 2022)

- [ ] **Alterar front do card (remover bullets de check):**
**DE:**
<img width="508" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVRVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9a99378ddaa05e0b5706478a4e8ea47d427d083/image.png" alt="image.png" />

**PARA:**
<img width="636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--481d0efc4c2bd652f1d9ae8f73470b24f833f75b/image.png" alt="image.png" />

---

**2. Municípios de médio/grande porte (aplicar no card atual):**

- [ ] **Alterar fonte de dados**
- Número de CRAS com forte articulação (municipios de porte médio e grande)
- Número total de CRAS por município (pegar o dado do ano do indicador acima, no caso 2022)

- [ ] Alterar front (texto) do card:
**DE: "CRAS com forte articulação..."**
<img width="613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW5VQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b4e93c74eb9ecedb182f17b51dd4fdbbb77eba7/image.png" alt="image.png" />

**PARA: "Pelo menos 20% de CRAS com forte articulação..."**
<img width="584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--663db1039e66a060bfd1608a86ebafde57840a93/image.png" alt="image.png" />

Definição de Preparado
- [x] Description
- [x] Regra
- [x] Exemplo/Protótipo
