### ISSUE TITLE
SPIKE

### ISSUE THREAD

**Issue by lucasferreiraunicef** [UNICEF01/Paineis-do-Selo#68]

**Comment by lucasferreiraunicef** [comment]
Integrations:

1 - PCJ ( Criterios Prazo e Qualidade(1 ponto por prazo e um por qualidade) ) (C. Aquiles)
2 - BAE (Manoel)
3 - https://1mio.com.br/ - (Felipe Gonzales)
4 - Portal SIPIA (Portal do Governo - É um BD onde os conselheiros tutelares precisam alimentar. Recebem casos de violência contra a criança. )
5 - https://ava.unicef.org.br/login/index.php (Moodle - Diogo) - OK
6 - BAV

**Comment by lucasferreiraunicef** [comment]
RS 1 

Para pontuar neste resultado, o município precisará entregar os 2 produtos abaixo e alcançar as 3 metas que aparecem no item VII.

- [ ] Plano Municipal Pela Primeira Infância (PMPI) postado na PCJ. Prazo: agosto 2022. 
- [ ] Plano Municipal Pela Primeira Infância implementado no município. Prazo: agosto 2023.
- [ ] Pelo menos 01 CRAS que oferece serviços de atenção à primeira infância até 31 de dezembro de 2023. No caso de municípios que tenham mais de 05 CRAS que pelo menos 20% tenham serviços de atenção.
- [ ] Garantir que pelo menos 30% das crianças matriculadas no município sejam beneficiadas por práticas qualificadas de Educação Infantil, em duas rodadas: 30% até março de 2023, e 30% até junho de 2024.
- [ ] Ter estratégia de Busca Ativa Vacinal (BAV) implementada no município até 31 de dezembro de 2022.

Questions:

1. Existe API na plataforma PCJ ? (Google Classroom)
2. Por onde é enviado o Plano Municipal Pela Primeira Infância implementado no município
3. Como é comprovado o  01 CRAS que oferece serviços de atenção à primeira infância até 31 de dezembro de 2023. No caso de municípios que tenham mais de 05 CRAS que pelo menos 20% tenham serviços de atenção.
4. Como é comprovado Garantir que pelo menos 30% das crianças matriculadas no município sejam beneficiadas por práticas qualificadas de Educação Infantil, em duas rodadas: 30% até março de 2023, e 30% até junho de 2024.
5. Como é comprovado Ter estratégia de Busca Ativa Vacinal (BAV) implementada no município até 31 de dezembro de 2022.

Dependency: 

API PCJ

Dúvidas
1. Por onde é enviado o Plano Municipal Pela Primeira Infância implementado no município?
De acordo com a equipe de Saúde abriremos um espaço na PCJ para obtermos esse documento;
 
2. Como é comprovado os "CRAS"? Já foi pensado isso?
A equipe de saúde está discutindo como será comprovado.
Porém, averiguei que esta informação está presente no Censo SUAS, mas é necessário conversa com a equipe para saber qual variável melhor representa o dado necessário.
 
3. Como é comprovado o seguinte item? -> Garantir que pelo menos 30% das crianças matriculadas no município sejam beneficiadas por práticas qualificadas de Educação Infantil, em duas rodadas: 30% até março de 2023, e 30% até junho de 2024.
De acordo com a equipe de educação da TAM, haverá uma Plataforma (que está em desenvolvimento) para que o município forneça as informações acima. Tb será possível obter os seguintes dados:
a) Descrição sintética das atividades realizadas (práticas de qualidade envolvendo autoavaliação, Deixa que Eu Conto e espaços adequados);
b) Número de escolas beneficiadas;
c) Número de crianças beneficiadas.
 
4. Como é comprovado o seguinte item? -> Ter estratégia de Busca Ativa Vacinal (BAV) implementada no município até 31 de dezembro de 2022.
A Plataforma está sendo construída e no final de dezembro haverá um exercício com 2 municípios piloto para entender como funcionará a Plataforma dentro da estratégia.

**Comment by lucasferreiraunicef** [comment]
RS 2

VII – META(S) QUE O MUNICÍPIO PRECISA ALCANÇAR NESTE RESULTADO SISTÊMICO 

1. Busca Ativa Escolar: 
Rematricular o equivalente a 40% do número de crianças e adolescentes que constarem como abandono no Censo Escolar em 2019 até março de 2023, e rematricular o equivalente a 40% do número de crianças e adolescentes que constarem como abandono no Censo Escolar em 2022 até junho de 2024. 


Rematrículas a partir de Nov/2021 até 31/03/2023

DADOS ORIÚNDOS DA BUSCA ATIVA ESCOLAR

2. Enfrentamento à cultura de fracasso escolar: 
Beneficiar pelo menos 30% do total de matrículas de crianças e adolescentes no ensino fundamental do município com ações de enfrentamento à cultura de fracasso escolar relacionadas ao desenvolvimento de competências e habilidades definidas pela BNCC em cada um dos ciclos de medição: março de 2023 e junho de 2024.


Atividades: 

1 ) Rematricular o equivalente a 40% do número de
crianças e adolescentes que constarem como abandono
no Censo Escolar em 201. 

Prazo: 31 de março de 2023

Source: Plataforma BAE


2 ) Beneficiar pelo menos 30% do total de matrículas de
crianças e adolescentes no ensino fundamental do
município com ações de enfrentamento à cultura de
fracasso escolar relacionadas ao desenvolvimento de
competências e habilidades definidas pela BNCC em
cada um dos ciclos de medição: março de 2023 e junho
de 2024.

Prazo: 31 de março de 2023

Source: Plataforma BAE


3 ) Rematricular o equivalente a 40% do número de crianças e adolescentes que constarem como abandono no Censo Escolar em 2022

Prazo: 30 de junho de 2024

Source: Plataforma BAE

4 ) Beneficiar pelo menos 30% do total de matrículas de
crianças e adolescentes no ensino fundamental do
município com ações de enfrentamento à cultura de
fracasso escolar relacionadas ao desenvolvimento de
competências e habilidades definidas pela BNCC em
cada um dos ciclos de medição: março de 2023 e junho
de 2024.

Prazo: 30 de junho de 2024

Source: Plataforma BAE

**Comment by lucasferreiraunicef** [comment]
RS 4

V – QUAL INDICADOR SERÁ UTILIZADO PARA AVALIAR O MUNICÍPIO? Percentual de adolescentes entre 15 e 17 anos que estão matriculados no ensino médio (Censo Escolar/ INEP/MEC com IBGE)

VI – O QUE O MUNICÍPIO PRECISA ENTREGAR, E QUAL O PRAZO? 

• Adesão do município à iniciativa 1 Milhão de Oportunidades (1MiO). Prazo: até 31 de maio de 2022. 

• Pelo menos 4 agentes públicos municipais capacitados, incluindo o(a) mobilizador de Adolescentes, no Curso Autoinstrucional Mobilização para Criar Oportunidades de Trabalho Decente, Aprendizagem, Educação e Profissionalização. Prazo: até 31 de dezembro de 2022.

• Número de oportunidades geradas para adolescentes e jovens (14 a 24 anos) em situação de vulnerabilidade, na gestão pública municipal e na articulação com outros setores produtivos local, reportadas na plataforma 1 Milhão de Oportunidades. Prazo: até 30 de junho de 2024


Atividades: 

1 ) Adesão do município à iniciativa 1 Milhão de Oportunidades -1MiO 

Prazo: 31 de maio de 2022

Source: https://1mio.com.br/

2 ) Pelo menos 4 agentes públicos municipais capacitados, incluindo o(a) mobilizador de Adolescentes, no Curso Auto

Prazo: 31 de dezembro de 2022

Source: https://1mio.com.br/

3 ) Número de oportunidades geradas para adolescentes e jovens (14 a 24 anos) em situação de vulnerabilidade, na gestão pública municipal e na articulação com outros setores produtivos local, reportadas na plataforma 1 Milhão de Oportunidades. Ver na tabela do Guia Metodológico do Selo o número de oportunidades a serem criadas de acordo com o tamanho da população do município

Prazo: 30 de junho de 2024

Source: www.1mio.org.br

**Comment by lucasferreiraunicef** [comment]
RS 5

V – QUAL INDICADOR SERÁ UTILIZADO PARA AVALIAR O MUNICÍPIO? Percentual de nascidos vivos de gestante de 10-19 anos (SINASC/MS). 

VI – O QUE O MUNICÍPIO PRECISA ENTREGAR, E QUAL O PRAZO? 

• Pelo menos 4 profissionais dos municípios capacitados em saúde mental. Prazo: até 31 de março de 2022. 

• Fluxo de atendimento de crianças e adolescentes em saúde mental definido. Prazo: até 30 de junho de 2022. 

• Serviços de atendimento psicossocial criados no município, ou indicação de um serviço existente em outro município para o qual os casos que demandem atenção especializada serão encaminhados. Prazo: até 31 de dezembro de 2022.


Atividades:

1 ) Pelo menos 4 profissionais dos municípios capacitados em pelo menos um dos cursos de saúde mental

Prazo: 30 de junho de 2022

Source: https://ava.unicef.org.br/login/index.php 

2 ) Fluxo de atendimento de crianças e adolescentes
em saúde mental definido

Prazo: 30 de junho de 2022

Source: PCJ (Google Classroom)

3 ) Serviços de atendimento psicossocial criados no município, ou indicação de um serviço existente em outro município para o qual os casos que demandem atenção especializada serão encaminhados.

Prazo: 31 de dezembro de 2022

Source: (Declaração do município informando a qual serviço os casos são encaminhados.) - PCJ (Google Classroom)

**Comment by lucasferreiraunicef** [comment]
RS 6

IV – O QUE O MUNICÍPIO PRECISA FAZER? 
1. Realizar ações de prevenção das violências contra crianças e adolescentes, por meio da: 

a) realização de oficinas nas escolas com utilização de materiais como as “Trilhas do Conhecimento” (do Canal Futura), a série “Que Corpo é Esse?” e a campanha do ECA 30, entre outros, com a participação de alunos e professores para abordar a prevenção da violência contra crianças e adolescentes e elaborar ações e/ou campanhas sobre o tema;

b) realização de oficinas com profissionais da saúde sobre prevenção de violências, que incluam a compreensão do problema (tipos de violências mais recorrentes, perfis de vítimas e agressores, local etc.), a identificação de riscos/vulnerabilidades e fatores protetivos, a identificação de estratégias de prevenção e os métodos de disseminação e implementação dessas estratégias no município;

c) oferta de formação entre pares para e pelos NUCAs nos seguintes temas: em resolução de conflitos, comunicação não- -violenta e estratégias de prevenção da violência gênero e racismo;

d) inserção, no PAIF e SCFV, de oficinas com famílias sobre prevenção da violência na primeira infância com foco na parentalidade positiva e prevenção da negligência e da disciplina punitiva (incluindo violência física, verbal, psicológica e sexual).

2. Criar um mecanismo de coordenação intersetorial para o atendimento integrado de crianças e adolescentes vítimas ou testemunhas de violência e, por meio dele, elaborar o fluxo e o protocolo conforme as diretrizes da Lei nº 13431/2017 e do Decreto nº 9603/2018, incluindo capacitação para as metodologias da escuta especializada e o depoimento especial.

3. Realizar ações: 

a) de promoção do uso do SIPIA para o registro dos casos de violência contra crianças e adolescentes atendidos pelos conselheiros tutelares. 

b) de fortalecimento de capacidades dos conselheiros tutelares e CRAS/CREAS para atuação em rede

VI – QUAL INDICADOR SERÁ UTILIZADO PARA AVALIAR O MUNICÍPIO? Percentual de registros de casos de violações de direitos contra crianças e adolescentes completos (SIPIA).

VII – O QUE O MUNICÍPIO PRECISA ENTREGAR, E QUAL O PRAZO?

• 5 ações e/ou campanhas de prevenção da violência contra crianças e adolescentes implementadas no município em 2022 e 2023 (Maio Laranja, trabalho infantil, menino Bernardo, racismo e outras). Prazos: dezembro de 2022 (5 ações e/ ou campanhas) e dezembro de 2023 (5 ações e/ou campanhas). 
Documento a ser apresentado pelo município: informe das campanhas realizadas, com indicação do número de pessoas alcançadas, a partir de formulário fornecido pelo UNICEF a ser preenchido pelo CMDCA.

• Mecanismos estabelecidos pela lei 13431/2017 e decreto 9603/2018 (mecanismo de coordenação, fluxo e protocolo) criados e funcionando no município. Prazo: dezembro de 2023.
Documento a ser apresentado pelo município: declaração do CMDCA sobre o status da implementação dos mecanismos previstos pela Lei nº 13431/2017 e Decreto nº 9603/2018 no município.

• Casos de violência contra crianças e adolescentes identificados pelos Conselhos Tutelares e registrados adequadamente no SIPIA. 
Prazo: dezembro de 2022 (1ª relação com dados anuais) e dezembro de 2023 (2ª relação com dados anuais).
 Documento a ser apresentado pelo município: dados atualizados anualmente no Eixo de Impacto Social do Selo a partir de relatórios extraídos do Portal SIPIA (MMFDH).


Atividades


1 ) Casos de violência contra crianças e adolescentes identificados pelos Conselhos Tutelares e registrados adequadamente no SIPIA (primeira relação com dados anuais)

Prazo: 31 de dezembro de 2022

Source: Dados atualizados anualmente no Eixo
de Impacto Social do Selo a partir de relatórios extraídos do Portal SIPIA (MMFDH)


2 ) 5 ações e/ou campanhas de prevenção da violência contra crianças e adolescentes implementadas no município em 2022 e 2023 (Maio Laranja, trabalho infantil, menino Bernardo, racismo e outras)

Prazo: 31 dezembro de 2022

Source: (Sim. UNICEF disponibilizará um formulário a ser preenchido pelo CMDCA para informar campanhas realizadas, número de pessoas alcançadas) - PCJ (Google Classroom)


3 ) Mecanismos estabelecidos pela lei 13431/2017 e decreto 9603/2018 (mecanismo de coordenação, fluxo e protocolo) criados e funcionando no município

Prazo: 31 de dezembro de 2023

Source: (Declaração do CMDCA sobre
o status da implementação dos mecanismos previstos pela Lei nº 13431/2017 e Decreto nº 9603/2018 no município) - PCJ (Google Classroom)


4 ) Casos de violência contra crianças e adolescentes identificados pelos Conselhos Tutelares e registrados adequadamente no SIPIA (segunda relação com dados anuais)

Prazo: 31 de dezembro de 2023

Source: (Dados atualizados anualmente no Eixo
de Impacto Social do Selo a partir de relatórios extraídos do Portal SIPIA (MMFDH))


5 ) 5 ações e/ou campanhas de prevenção da violência contra crianças e adolescentes implementadas no município em 2022 e 2023 (Maio Laranja, trabalho infantil, menino Bernardo, racismo e outras)

Prazo: 31 de dezembro de 2023

Source: (Sim. UNICEF disponibilizará um formulário a ser preenchido pelo CMDCA para informar campanhas realizadas, número de pessoas alcançadas.) - PCJ (Google Classroom)
